name: EC2-Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
      - '.github/workflows/github-actions-ec2.yml'

jobs:
  deploy:
    name: Deploy riffly to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "server/"
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
          SCRIPT_AFTER: |
            sudo apt -y update
            sudo apt install -y redis
            sudo apt install -y nodejs 
            sudo apt install -y npm
            sudo npm install -g pm2
            cd dist
            sudo npm i
            touch .env
            echo "${{ secrets.API_ENV }}" > .env
            redis-cli flushall
            redis-cli shutdown
            redis-server ./redis.conf --daemonize yes
            sudo pm2 stop server
            sudo pm2 delete server
            sudo pm2 start server.js
