name: Oracle-Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'
      - '.github/workflows/github-actions-oci.yml'

jobs:
  deploy:
    name: Deploy riffly to Oracle on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Run CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: riffly-build

      - name: Copy S3 files
        run: aws s3 sync s3://riffly-dist .

      - name: Deploy to Oracle
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ORACLE_KEY }}
          REMOTE_HOST: ${{ secrets.ORACLE_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ORACLE_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.ORACLE_KEY }}
          script: |
            sudo apt -y update
            sudo npm install -g pm2 
            sudo npm install -g serve
            cd dist
            sudo pm2 stop client
            sudo pm2 delete client
            sudo pm2 start --name="client" sudo -- serve -s client/browser -c ../../serve.json -l 80
